### ISSUE TITLE
サイドメニューの項目名とアイコンを変更

### ISSUE THREAD

**Issue by Jumpei-Arigaya** [Jumpei-Arigaya/beator-front-web#3]
### やること
-  項目名を以下の内容に変更
    - 楽曲一覧
    - 楽曲新規作成
    - プロフィール

- アイコンを変更
  - [material-icons](https://mui.com/material-ui/material-icons/)で良いものがあればここから取得して表示
  - なければWEB上で見つけるか自分で作ってもOK

### 対象ファイル
beator-front-web/src/components/layouts/DashBoard.tsx

### UIで使用しているライブラリ（MUI）の説明ページ
https://mui.com/material-ui/react-drawer/#persistent-drawer:~:text=)%3B%0A%7D-,Persistent%20drawer,-Persistent%20navigation%20drawers

**Comment by nonchimaru** [comment]
ああ

**Comment by nonchimaru** [comment]
あああ

**Comment by Jumpei-Arigaya** [comment]
test
