### ISSUE TITLE
プロフィール画面の要件定義・設計

### ISSUE THREAD

**Issue by Jumpei-Arigaya** [Jumpei-Arigaya/beator-front-web#32]
- プロフィール画面の実装をする前段階として仕様を決定する
- 下記のリンク先のページにまとめる
  - https://github.com/Jumpei-Arigaya/beator-front-web/wiki/%E3%83%97%E3%83%AD%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E7%94%BB%E9%9D%A2

**Comment by Jumpei-Arigaya** [comment]
## デザインで気になった点
- プロフィールを登録・修正する方法（デザイン）
  - 楽器
  - 自己紹介文
- 楽器名がなにを表しているのかタイトルをつけたほうがいい気がする
- 楽器が30個くらい登録されたらどのような表示になるか
- 表示できる文字数は、画面の表示幅によって変わりそうだから、定義するなら登録できる最大文字数だけで良いかな（自己紹介文）

**Comment by nonchimaru** [comment]
文字数は最大180文字を限度にしました。
16個の楽器名を設定できるようにしました。実際の画面の比率に合わせてタグの大きさも変える予定ですが、現在の画面上の配置範囲を超える量になる場合は、配置場所自体も変更する予定です。

**Comment by Jumpei-Arigaya** [comment]
> 文字数は最大180文字を限度にしました。
16個の楽器名を設定できるようにしました。実際の画面の比率に合わせてタグの大きさも変える予定ですが、現在の画面上の配置範囲を超える量になる場合は、配置場所自体も変更する予定です。

了解です！
あとプロフィールを登録・修正する方法はどうする？
プロフィール設定ボタンが押されたら、そのまま同じ画面上で入力できるようにするか、モーダル（小画面）が立ち上がって修正するみたいな感じかな？
どっちのパターンにしても、楽器を登録する入り口のデザインが必要そう！
![image](https://github.com/Jumpei-Arigaya/beator-front-web/assets/97542063/28d8ed27-b8d5-49b4-beac-50dd1b7b2b9b)

**Comment by nonchimaru** [comment]
確かに。
てか、このプロフィール画面は他のユーザーに見られるタイプのプロフィールだよね？

**Comment by Jumpei-Arigaya** [comment]
> 確かに。
> 
> てか、このプロフィール画面は他のユーザーに見られるタイプのプロフィールだよね？

そうだね、インスタとかTwitterのプロフィールと同じ！
自分のプロフィールを開いたときだけ編集可能。

**Comment by nonchimaru** [comment]
モーダルを立ち上げてプロフィール編集する感じが良いと思います。モーダルもFigmaで設計する感じですか？

**Comment by Jumpei-Arigaya** [comment]
> モーダルを立ち上げてプロフィール編集する感じが良いと思います。モーダルもFigmaで設計する感じですか？

簡単で良いのでデザイン起こしましょう！
