### ISSUE TITLE
ヘッダのpx数を定数で管理できるようにする

### ISSUE THREAD

**Issue by Jumpei-Arigaya** [Jumpei-Arigaya/beator-front-web#35]
404エラーページやヘッダなどで、64pxという数値が直接入力されているが、変更があった場合に、すべての箇所の変更が必要な状態になっている。
定数で定義してそれを各ファイルで読み込んで使用する形にする。
 → 今後、高さが変わった場合に一箇所だけ変更するだけで対応が終わる

**Comment by nonchimaru** [comment]
例えば404エラーページでいうと`const marginTopValue = "-64px";`これの追加と` marginTop: marginTopValue,`これに書き換えればいいってこと？

**Comment by Jumpei-Arigaya** [comment]
@nonchimaru 
beator-front-web/src/styles の中にlayout.tsをつくって、その中にheaderHightを64pxで定義する
それを各コンポーネントで読み込む形かな
